import os

DOWNSTREAM_LATENCY_MS = float(os.getenv("DOWNSTREAM_LATENCY_MS", "200"))
FAILURE_RATE = float(os.getenv("FAILURE_RATE", "0.5"))

NAIVE_MAX_RETRIES = int(os.getenv("NAIVE_MAX_RETRIES", "5"))
BACKOFF_MAX_RETRIES = int(os.getenv("BACKOFF_MAX_RETRIES", "3"))
BACKOFF_BASE_SECONDS = float(os.getenv("BACKOFF_BASE_SECONDS", "0.2"))

CIRCUIT_FAILURE_THRESHOLD = int(os.getenv("CIRCUIT_FAILURE_THRESHOLD", "5"))
CIRCUIT_OPEN_SECONDS = float(os.getenv("CIRCUIT_OPEN_SECONDS", "10"))
